### ISSUE TITLE
Firefox extension, Azure dev Ops integration : display issue

### ISSUE THREAD

**Issue by Ludogo** [clockify/browser-extension#183] opened 2022-04-07 11:26 UTC
For two days i have some issue with Firefox Extension on Linux.
I didn't test on other plateform. 
![image](https://user-images.githubusercontent.com/9932379/162188238-c2c7b759-cf0e-4ba8-820d-92bbd333013f.png)

Firefox version : 99.0 (64 bits): Snap version
Linux : ubuntu 18.04 LTS

**Comment by Legiew** [comment] 2022-04-08 14:33
Same here with Chrome 100.0.4896.60 on Mac OS

**Comment by strahinjaclockify** [comment] 2022-04-11 07:58
Hi @Ludogo and @Legiew, thanks for letting us know about the issue with your Azure Dev ops integration. Can you please reinstall Clockify extension and let us know if that solved the issue? Thanks!

**Comment by Ludogo** [comment] 2022-04-11 08:17
Hello,
i've just made it, and it's still the same

**Comment by juliangrube1988** [comment] 2022-04-11 11:14
Same here with Chrome 98.0.4758.102 and extension Version 2.1.0

**Comment by strahinjaclockify** [comment] 2022-04-11 11:54
Thanks for getting back to me, @Ludogo, @juliangrube1988. We're very sorry for the inconvenience caused.

Can you please check your language in [Clockify's Profile settings](https://app.clockify.me/user/settings)? If the value is set to System default, please update the language to English (or other if you prefer). Once updated, please reinstall, and let me know if that resolves the issue.

**Comment by juliangrube1988** [comment] 2022-04-11 12:38
> Thanks for getting back to me, @Ludogo, @juliangrube1988. We're very sorry for the inconvenience caused.
> 
> Can you please check your language in [Clockify's Profile settings](https://app.clockify.me/user/settings)? If the value is set to System default, please update the language to English (or other if you prefer). Once updated, please reinstall, and let me know if that resolves the issue.

Thanks, that resolves it for me

**Comment by Ludogo** [comment] 2022-04-11 13:34
It doesn't work for me for French language. 
I will test with English as soon as i can.

**Comment by strahinjaclockify** [comment] 2022-04-11 18:12
@Ludogo, please make sure that French is explicitly selected in your [Profile settings](https://app.clockify.me/user/settings). Thank you.

**Comment by clementmbr** [comment] 2022-04-13 08:47
Same problem here with Firefox 99.0 and Ubuntu 20.04 LTS

**Comment by strahinjaclockify** [comment] 2022-04-13 09:06
Hi @Ludogo, @clementmbr - thanks for your replies. Can you please follow the steps below so we can troubleshoot the issue better and make sure it's resolved in the next update? Thanks!

Here are the steps:
1. Open chrome://extensions
2. Enable developer mode in top right corner
3. Click on service worker link on Clockify extension card
4. Keep new window open while reproducing bug
5. Open extension - logout/login
6. Reproduce bug - Go to azure, refresh page 
7. Take screenshot of opened console window

**Comment by clementmbr** [comment] 2022-04-13 09:42
@strahinjaclockify does this help?

![image](https://user-images.githubusercontent.com/31664455/163147493-69e5f6cd-1cfc-4836-8f80-5cb078b0dd40.png)

An extract from the quoted code :
```
  applySafeWithoutClone(callback, args, caller) {
    if (this.unloaded) {
      Cu.reportError(
        "context.runSafeWithoutClone called after context unloaded",
        caller
      );
    } else if (!this.active) {
      Cu.reportError(
        "context.runSafeWithoutClone called while context is inactive",
        caller
      );
    } else {
      try {
        return Reflect.apply(callback, null, args);
      } catch (e) {
        dump(
          `Extension error: ${e} ${e.fileName} ${
            e.lineNumber
          }\n[[Exception stack\n${filterStack(e)}Current stack\n${filterStack(
            Error()
          )}]]\n`
        );
        Cu.reportError(e);
      }
    }
  }
```
and
```
  wrapPromise(promise, callback = null) {
    let caller = this.getCaller();
    let applySafe = this.applySafe.bind(this);
    if (Cu.getGlobalForObject(promise) === this.cloneScope) {
      applySafe = this.applySafeWithoutClone.bind(this);
    }

    if (callback) {
      promise.then(
        args => {
          if (this.unloaded) {
            Cu.reportError(`Promise resolved after context unloaded\n`, caller);
          } else if (!this.active) {
            Cu.reportError(
              `Promise resolved while context is inactive\n`,
              caller
            );
          } else if (args instanceof NoCloneSpreadArgs) {
            this.applySafeWithoutClone(callback, args.unwrappedValues, caller);
          } else if (args instanceof SpreadArgs) {
            applySafe(callback, args, caller);
          } else {
            applySafe(callback, [args], caller);
          }
        },
        error => {
          this.withLastError(error, caller, () => {
            if (this.unloaded) {
              Cu.reportError(
                `Promise rejected after context unloaded\n`,
                caller
              );
            } else if (!this.active) {
              Cu.reportError(
                `Promise rejected while context is inactive\n`,
                caller
              );
            } else {
              this.applySafeWithoutClone(callback, [], caller);
            }
          });
        }
      );
    } else {
      return new this.Promise((resolve, reject) => {
        promise.then(
          value => {
            if (this.unloaded) {
              Cu.reportError(
                `Promise resolved after context unloaded\n`,
                caller
              );
            } else if (!this.active) {
              Cu.reportError(
                `Promise resolved while context is inactive\n`,
                caller
              );
            } else if (value instanceof NoCloneSpreadArgs) {
              let values = value.unwrappedValues;
              this.applySafeWithoutClone(
                resolve,
                values.length == 1 ? [values[0]] : [values],
                caller
              );
            } else if (value instanceof SpreadArgs) {
              applySafe(resolve, value.length == 1 ? value : [value], caller);
            } else {
              applySafe(resolve, [value], caller);
            }
          },
          value => {
            if (this.unloaded) {
              Cu.reportError(
                `Promise rejected after context unloaded: ${value &&
                  value.message}\n`,
                caller
              );
            } else if (!this.active) {
              Cu.reportError(
                `Promise rejected while context is inactive: ${value &&
                  value.message}\n`,
                caller
              );
            } else {
              this.applySafeWithoutClone(
                reject,
                [this.normalizeError(value, caller)],
                caller
              );
            }
          }
        );
      });
    }
  }
```

FYI the problem is not specific to Azure, it appears all over Firefox, even in the Clockify extension settings :
![image](https://user-images.githubusercontent.com/31664455/163148366-b4b1139f-44f5-446b-ae7f-679d58ae22dd.png)

**Comment by strahinjaclockify** [comment] 2022-04-14 13:35
Hi @Ludogo, @clementmbr - an update for Firefox has just been published (Chrome coming soon). Can you please update your extension and let us know if the issue persists? Thanks again!

**Comment by viantirreau** [comment] 2022-04-14 18:47
@strahinjaclockify it works for me now, I was having the same problem in Firefox.
Thanks a lot!!

**Comment by Ludogo** [comment] 2022-04-15 06:48
@strahinjaclockify It's working great now ! \o/ 
Thank you so much.

**Closed** 2022-04-15 06:49 UTC

**Comment by clementmbr** [comment] 2022-04-15 07:34
Thanks @strahinjaclockify !
